/**
 * Decorative Image Registry for Poetry tags.
 *
 * Keys are exact tag strings (case-sensitive, alphabetical order).
 * Values are image FILENAMES only (e.g. "rose.png") stored under
 * apps/dad-site/public/poetry/, or null when unmapped.
 *
 * Run `npm run sync:decorative-images` (from apps/dad-site) to add
 * any missing tags discovered in the poetry collection.
 */
export const DECORATIVE_IMAGE_REGISTRY: Record<string, string | null> = {
	"1940s": null,
	"1949": null,
	"Abstract": null,
	"age": null,
	"Aging": null,
	"Alfa Romeo": "car.png",
	"Alfa Romero": "car.png",
	"Aquarium of the Pacific": null,
	"architecture": null,
	"art": null,
	"art exhibition": null,
	"auditions": null,
	"authority": null,
	"automobiles": "car.png",
	"Bert": null,
	"Billboard": null,
	"biography": null,
	"bird": null,
	"black humor": null,
	"Bob Dylan": null,
	"brotherhood": null,
	"builder": null,
	"building": null,
	"buildings": null,
	"bull": null,
	"bull pen": null,
	"By The Skin Of Our Teeth": null,
	"cars": "car.png",
	"Casie": null,
	"cats": null,
	"cellphones": null,
	"childhood": null,
	"children": null,
	"Christmas": null,
	"Christmas songs": null,
	"church": null,
	"city": null,
	"coffee": null,
	"college": null,
	"consciousness": null,
	"construction": null,
	"courage": null,
	"culture": null,
	"dairy farm": null,
	"dancing": null,
	"dark humor": null,
	"daydreaming": null,
	"Death": null,
	"death": null,
	"desert": null,
	"design": null,
	"draft": null,
	"drama": null,
	"dreams": null,
	"driving": null,
	"Easter": null,
	"Edgar Degas": null,
	"Education": null,
	"el segundo dairy": null,
	"Eugene O'Neill": null,
	"Family": null,
	"family": null,
	"family gathering": null,
	"father": null,
	"fatherhood": null,
	"Fiat": "car.png",
	"Film": null,
	"film": null,
	"fine art": null,
	"flowers": null,
	"food": null,
	"Fort Ord": null,
	"funeral": null,
	"giraffe": null,
	"growing-up": null,
	"growth": null,
	"hawk": null,
	"heat": null,
	"Henri Matisse": null,
	"high school": null,
	"History": null,
	"history": null,
	"holidays": null,
	"hope": null,
	"house": null,
	"inspiration": null,
	"Jack": null,
	"Jean Renoir": null,
	"Jimmy Carter": null,
	"Korea": null,
	"life": null,
	"Lion In Winter": null,
	"Little Poems": null,
	"Meditations": null,
	"memory": null,
	"Metaphor": null,
	"MGTD": null,
	"mobile home": null,
	"mortality": null,
	"mother": null,
	"movies": null,
	"moving": null,
	"museum": null,
	"museum exhibition": null,
	"music": null,
	"nature": null,
	"neighbor": null,
	"Neil Diamond": null,
	"Nelson Rockefeller": null,
	"New Mexico": null,
	"Nicole": null,
	"On the Road": null,
	"Our Town": null,
	"pacifism": null,
	"painting": null,
	"passion": null,
	"Philosophy": null,
	"Places": null,
	"plays": null,
	"playwriting": null,
	"politics": null,
	"porch": null,
	"Porsche": null,
	"Portales": null,
	"productivity": null,
	"pulled-over": null,
	"randall dairy el segundo": null,
	"religion": null,
	"Renaissance Man": null,
	"sadness": null,
	"Sand Dunes Tavern": null,
	"Santa Claus": null,
	"Sausage McMuffin": null,
	"seasons": null,
	"Shakespeare": "rose.png",
	"Shakespearean": "rose.png",
	"Silver Street": null,
	"singing": null,
	"street": null,
	"streets": null,
	"students": null,
	"Sue": null,
	"summer": null,
	"teaching": null,
	"Teahouse of the August Moon": null,
	"teenagers": null,
	"Theatre": "drama.png",
	"theatre": "drama.png",
	"Thornton Wilder": null,
	"THS": null,
	"Time": null,
	"time": null,
	"toad": null,
	"Torrance": null,
	"Torrance High School": null,
	"train tracks": null,
	"trains": null,
	"traveling": null,
	"Truman": null,
	"urban": null,
	"Vanagan": null,
	"veteran": null,
	"War": "war.png",
	"war": "war.png",
	"wind": null,
	"winter": null,
	"wood carving": null,
	"work": null,
	"worship": null,
	"WWI": null,
	"xmas": null,
	"zen": null,
	"Ziggy": null,
};

/**
 * Returns the resolved image path `/poetry/<filename>` if the tag is
 * mapped in the registry, otherwise returns null.
 * This is the ONLY place that prepends `/poetry/`.
 */
export function getDecorativeImageForTag(tag: string): string | null {
	const filename = DECORATIVE_IMAGE_REGISTRY[tag];
	return filename ? `/poetry/${filename}` : null;
}

/** Returns true if the tag exists as a key in the registry. */
export function hasRegistryTag(tag: string): boolean {
	return Object.prototype.hasOwnProperty.call(DECORATIVE_IMAGE_REGISTRY, tag);
}

/** Returns all registry tag keys, sorted alphabetically (case-insensitive). */
export function getRegistryTags(): string[] {
	return Object.keys(DECORATIVE_IMAGE_REGISTRY).sort((a, b) =>
		a.localeCompare(b, undefined, { sensitivity: 'base' })
	);
}
